nodeLinker: node-modules

plugins:
  - checksum: 60c276fb3affe5b6b75a77241564cb61d79592212660b53010b80c99c45a7fdaff333db0dda304a41271472fb01cdd325000af5ae4fd1629778e2e01b15133bc
    path: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs
    spec: "https://github.com/CycloneDX/cyclonedx-node-yarn/releases/latest/download/yarn-plugin-cyclonedx.cjs"
