name = "tea"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
pages_build_output_dir = "./dist"

[limits]
cpu_ms = 3000

[[d1_databases]]
binding = "d1db"
database_name = "tea"
database_id = "d1:example-database-id"

[[r2_buckets]]
binding = 'r2artifacts'
bucket_name = 'artifacts'
